import AdequacyArchitecture.Residual.CanonicalCarrier
import AdequacyArchitecture.Residual.Geometry
import AdequacyArchitecture.Residual.Composition
import AdequacyArchitecture.Residual.Recovery
import AdequacyArchitecture.Residual.JointObservability
