import AdequacyArchitecture.Adjudication.ForcedAdjudication
import AdequacyArchitecture.Adjudication.NoCollapse
import AdequacyArchitecture.Adjudication.Carrier
import AdequacyArchitecture.Adjudication.Realization
